/*
 *    Copyright (c) 2012-2019, 2023 Qualcomm Technologies, Inc.
 *    All Rights Reserved.
 *    Confidential and Proprietary - Qualcomm Technologies, Inc.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qualcomm_listen_ListenSoundModel */

#ifndef _Included_com_qualcomm_listen_ListenSoundModel
#define _Included_com_qualcomm_listen_ListenSoundModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    nativeGetSMLVersion
 * Signature: (Lcom/qualcomm/listen/ListenTypes/SMLVersion;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_nativeGetSMLVersion
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    nativeVerifyUserRecording
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;Ljava/nio/ShortBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_nativeVerifyUserRecording
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    nativeVerifyUserRecordingQuality
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;Ljava/nio/ShortBuffer;ZLcom/qualcomm/listen/ListenTypes/QualityCheckInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_nativeVerifyUserRecordingQuality
  (JNIEnv *, jclass, jobject, jstring, jobject, jboolean, jobject);

/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    nativeSetSoundModelTuningParams
 * Signature: (ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_nativeSetSoundModelTuningParams
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    nativeGetSizeWhenExtended
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_nativeGetSizeWhenExtended
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    nativeExtend
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;Ljava/lang/String;
 *             I[Ljava/nio/ShortBuffer;Ljava/nio/ByteBuffer;
 *             Lcom/qualcomm/listen/ListenTypes/ConfidenceData;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_nativeExtend
  (JNIEnv *, jclass, jobject, jstring, jstring, jint, jobjectArray, jobject, jobject);

/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    nativeVerifyUdkRecording
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ShortBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_nativeVerifyUdkRecording__Ljava_nio_ByteBuffer_2Ljava_nio_ShortBuffer_2
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    nativeVerifyUdkRecording
 * Signature: (Ljava/nio/ByteBuffer;[Ljava/nio/ShortBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_nativeVerifyUdkRecording__Ljava_nio_ByteBuffer_2_3Ljava_nio_ShortBuffer_2
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    nativeGetUdkSmSize
 * Signature: (Ljava/lang/String;Ljava/lang/String;[[Ljava/nio/ShortBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_nativeGetUdkSmSize
  (JNIEnv *, jclass, jstring, jstring, jobjectArray, jobject);

/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    nativeCreateUdkSm
 * Signature: (Ljava/lang/String;Ljava/lang/String;I[[Ljava/nio/ShortBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Lcom/qualcomm/listen/ListenTypes/ConfidenceData;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_nativeCreateUdkSm
  (JNIEnv *, jclass, jstring, jstring, jint, jobjectArray, jobject, jobject, jobject);


/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    parseVWUDetectionEventData
 * Signature: (Ljava/nio/ByteBuffer;Lcom/qualcomm/listen/ListenTypes/EventData;
 *             Lcom/qualcomm/listen/ListenTypes/VoiceWakeupDetectionData;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_parseVWUDetectionEventData
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    parseVWUDetectionEventDataV2
 * Signature: (Ljava/nio/ByteBuffer;Lcom/qualcomm/listen/ListenTypes/EventData;
 *             Lcom/qualcomm/listen/ListenTypes/VoiceWakeupDetectionDataV2;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_parseVWUDetectionEventDataV2
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    nativeGetTypeVersion
 * Signature: (Ljava/nio/ByteBuffer;Lcom/qualcomm/listen/ListenTypes/SoundModelInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_nativeGetTypeVersion
  (JNIEnv *, jclass, jobject, jobject);


/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    getInfo
 * Signature: (Ljava/nio/ByteBuffer;Lcom/qualcomm/listen/ListenTypes/SVASoundModelInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_getInfo
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    nativeMerge
 * Signature: ([Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_nativeMerge
                (JNIEnv *, jclass, jobjectArray, jobject);

/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    nativeGetSizeWhenMerged
 * Signature: ([Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_nativeGetSizeWhenMerged
                (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    nativeDeleteData
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;Ljava/lang/String;
 *             Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_nativeDeleteData
  (JNIEnv *, jclass, jobject, jstring, jstring, jobject);

/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    nativeGetSizeAfterDelete
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_nativeGetSizeAfterDelete
  (JNIEnv *, jclass, jobject, jstring, jstring);


#ifdef __cplusplus
}
#endif
#endif
