/*****************************************************************************
  Copyright (c) 2020 Qualcomm Technologies, Inc.
  All rights reserved.
  Confidential and Proprietary - Qualcomm Technologies, Inc.
*****************************************************************************/

// This class implements the IDiagnostics interface.
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define CDiagnostics_UID UINT32_C(143)


