// Copyright (c) 2015, 2021 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
// IModule.idl
//
// This interface requests objects from modules.
/** @cond */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define IModule_ERROR_NOT_FOUND INT32_C(10)

#define IModule_OP_open 0
#define IModule_OP_shutdown 1

static inline int32_t
IModule_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IModule_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
IModule_open(Object self, uint32_t id_val, Object credentials_val, Object *obj_ptr)
{
  ObjectArg a[3]={{{0,0}}};
  a[0].b = (ObjectBuf) { &id_val, sizeof(uint32_t) };
  a[1].o = credentials_val;

  int32_t result = Object_invoke(self, IModule_OP_open, a, ObjectCounts_pack(1, 0, 1, 1));

  *obj_ptr = a[2].o;

  return result;
}

static inline int32_t
IModule_shutdown(Object self)
{
  return Object_invoke(self, IModule_OP_shutdown, 0, 0);
}



