/*****************************************************************************
  Copyright (c) 2020 Qualcomm Technologies, Inc.
  All rights reserved.
  Confidential and Proprietary - Qualcomm Technologies, Inc.
*****************************************************************************/
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"


static inline int32_t
IObject_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IObject_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}



