/********************************************************************
Copyright (c) 2020 Qualcomm Technologies, Inc.
All Rights Reserved.
Confidential and Proprietary - Qualcomm Technologies, Inc.
*********************************************************************/

/** @file  IOpener.idl */
/** @cond */
/** 0 is not a valid service ID. */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"
#include "IOpener.h"

#define IOpener_DEFINE_INVOKE(func, prefix, type) \
  int32_t func(ObjectCxt h, ObjectOp op, ObjectArg *a, ObjectCounts k) \
  { \
    type me = (type) h; \
    switch (ObjectOp_methodID(op)) { \
      case Object_OP_release: { \
        return prefix##release(me); \
      } \
      case Object_OP_retain: { \
        return prefix##retain(me); \
      } \
      case IOpener_OP_open: { \
        if (k != ObjectCounts_pack(1, 0, 0, 1) || \
          a[0].b.size != 4) { \
          break; \
        } \
        const uint32_t *id_ptr = (const uint32_t*) a[0].b.ptr; \
        return prefix##open(me, *id_ptr, &a[1].o); \
      } \
    } \
    return Object_ERROR_INVALID; \
  }


