/** @file ITAccessPermissions.idl */
// Copyright (c) 2023 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
// include "ICredentials.idl"
/**
  ITAccessPermissions provides definition of data structures for confinement.
*/
// ITAccessPermissions are optional and only required
//   when memory must be confined to specific users only.
/**
 * @addtogroup ITAccessPermissions
 * @{
 */
/** @cond */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

typedef struct {
  uint64_t uid;
  uint64_t perms;
} ITAccessPermissions_uidBasedPerms;

typedef struct {
  uint64_t did;
  uint64_t perms;
} ITAccessPermissions_didBasedPerms;

#define ITAccessPermissions_keepSelfAccess UINT64_C(0)

#define ITAccessPermissions_removeSelfAccess UINT64_C(1)

#define ITAccessPermissions_smmuProxyControlled UINT64_C(2)

#define ITAccessPermissions_mixedControlled UINT64_C(4)

typedef struct {
  ITAccessPermissions_uidBasedPerms uidPermsList[5];
  ITAccessPermissions_didBasedPerms didPermsList[5];
  uint64_t specialRules;
} ITAccessPermissions_rules;


